### ISSUE TITLE
Deploy docs to domain

### ISSUE THREAD

**Issue by jwjeffr** [Chicago-Club-Management-Company/aqua-blue#9]
`sphinx` is the tool we are using to create the documentation.

We should be deploying the docs to an actual domain. Currently, the docs are being built upon every push in [publish.yml](https://github.com/Chicago-Club-Management-Company/aqua-blue/blob/main/.github/workflows/publish.yml).

Within this workflow, the docs are created, and an artifact named `sphinx-docs` is uploaded. There is currently a blank `deploy-docs` job that is downloading the artifact, and then doing nothing with it:

```yml
deploy-docs:
    needs:
      - create-docs
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Download docs artifact
        uses: actions/download-artifact@v4
        with:
          name: sphinx-docs
          path: html/

      # deploy here
      - name: Deploy documentation
        run: >-
          :
```

An example of such artifact is downloadable [here](https://github.com/Chicago-Club-Management-Company/aqua-blue/actions/runs/13274930168/artifacts/2575334341), which is just a folder of static html files, so it should be able to deploy this file to a server. Within this workflow, we should be deploying to a real website. We can hide the necessary keys as GitHub secret variables.
